{{- range $key, $val := .Values.build}}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: "{{$.Values.prefix}}-pipeline-template-push-{{- $key -}}"
spec:
  params:
    - name: gitrevision
      description: The git revision (SHA)
      default: master
    - name: gitbranch
      description: The git branch
      default: master
    - name: gitrepositoryurl
      description: The git repository url ("https://github.com/batleforc/rust-template")
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{$.Values.prefix}}-pipeline-push-{{- $key -}}-run-
      spec:
        pipelineRef:
          name: {{$.Values.prefix}}-pipeline-push
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
                storageClassName: local-path
          {{- range $key, $value := $.Values.secrets }}
          {{- if ne $key "githubTokenWebhook" }}
          - name: {{ $key }}
            secret:
              secretName: {{ $value }}
          {{- end }}
          {{- end }}
        params:
          - name: repo-revision
            value: $(tt.params.gitrevision)
          - name: repo-branch
            value: $(tt.params.gitbranch)
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)
          - name: conteneurfile-path
            value: "{{ $val.file_path }}"
          - name: image-name
            value: "{{ $.Values.image.registry }}/{{ $val.imageName }}"
          - name: helm-path
            value: "{{ $val.helm }}"
          - name: githubSecretName
            value: "{{ $.Values.secrets.githubTokenApi }}"
          - name: release-name
            value: "{{ $key }}"
{{- end}}