apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: folio-api
  description: Provide content of the portfolio
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/batleforc/Monofolio/refs/heads/main/.spectral.yaml
spec:
  type: openapi
  lifecycle: production
  owner: WeeboDev
  system: infra
  definition:
    $text: ./swagger.json
