pre_bump_hooks = ["RUST_BUMP_VERSION=\"{{version}}\" nx run-many -t bump"]
post_bump_hooks = ["git push", "git push origin {{version}}"]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "batleforc"
owner = "MonoFolio"
authors = [
    { username = "batleforc", signature = "Max" },
    { username = "max", signature = "Max" },
]

[bump_profiles]

[packages]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
commit_msg=$(cat "${1:?Missing commit message file}")
echo $commit_msg
export COMMIT_MSG=$commit_msg
nx run-many -t hook --verbose
"""
