[package]
name = "back"
version = "0.1.0"
edition = "2021"
default-run = "server"


[dependencies]
chrono = { version = "0.4", features = ["serde"] }
markdown_header = { path = "../../libs/markdown_header" }
markdown_struct = { path = "../../libs/markdown_struct" }
tool_tracing = { path = "../../libs/tool_tracing" }
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
tokio = "1.39"
dotenvy = "0.15.7"
tracing = "0.1.40"

# Code that handle the CLI
[[bin]]
name = "server"
path = "src/main.rs"
test = true

# Code for development purpose
[[bin]]
name = "sandbox"
path = "src/bin/sandbox.rs"
test = false
