[package]
name = "back"
version = "0.1.0"
edition = "2021"
default-run = "server"


[dependencies]
markdown-parser = "0.1.2"
serde = "1.0.204"
serde_json = "1.0.120"
serde_yaml = "0.9.34"

# Code that handle the CLI
[[bin]]
name = "server"
path = "src/main.rs"
test = true

# Code for development purpose
[[bin]]
name = "sandbox"
path = "src/bin/sandbox.rs"
test = false
