[package]
name = "back"
version = "0.1.0"
edition = "2021"
default-run = "server"


[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
chrono-tz = { version = "0.9.0", features = ["serde"] }
markdown_header = { path = "../../libs/markdown_header" }
serde = "1.0.204"
serde_json = "1.0.120"
serde_yaml = "0.9.34"
url = "2.5.2"

# Code that handle the CLI
[[bin]]
name = "server"
path = "src/main.rs"
test = true

# Code for development purpose
[[bin]]
name = "sandbox"
path = "src/bin/sandbox.rs"
test = false
