// This file is auto-generated by @hey-api/openapi-ts

export const $BlogTimeline = {
    type: 'object',
    required: ['pages'],
    properties: {
        pages: {
            type: 'object',
            additionalProperties: {
                '$ref': '#/components/schemas/PageShort'
            }
        }
    }
} as const;

export const $DocCategory = {
    type: 'object',
    required: ['name', 'has_index', 'sub_categories', 'pages'],
    properties: {
        has_index: {
            type: 'boolean'
        },
        name: {
            type: 'string'
        },
        pages: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/PageShort'
            }
        },
        sub_categories: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DocCategory'
            }
        }
    }
} as const;

export const $DocHeader = {
    type: 'object',
    required: ['title', 'date'],
    properties: {
        date: {
            type: 'string',
            format: 'date-time'
        },
        description: {
            type: 'string',
            nullable: true
        },
        links: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DocHeaderLink'
            }
        },
        spec: {
            '$ref': '#/components/schemas/DocHeaderSpec'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        techno: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        title: {
            type: 'string'
        },
        weight: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const $DocHeaderLink = {
    type: 'object',
    required: ['name', 'url'],
    properties: {
        name: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const $DocHeaderSpec = {
    type: 'object',
    properties: {
        blog: {
            type: 'boolean'
        },
        doc: {
            type: 'boolean'
        },
        project: {
            type: 'boolean'
        }
    }
} as const;

export const $HomeContent = {
    type: 'object',
    required: ['name', 'presentation', 'coverTitle', 'cvUrl', 'url', 'history'],
    properties: {
        coverTitle: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        cvUrl: {
            type: 'string'
        },
        history: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/HomeHistory'
            }
        },
        name: {
            type: 'string'
        },
        presentation: {
            type: 'string'
        },
        url: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/HomeUrl'
            }
        }
    }
} as const;

export const $HomeHistory = {
    type: 'object',
    required: ['title', 'lieux', 'date', 'weight', 'imgUrl', 'description'],
    properties: {
        date: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        imgUrl: {
            type: 'string'
        },
        lieux: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        url: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/HomeHistoryUrl'
            },
            nullable: true
        },
        weight: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const $HomeHistoryUrl = {
    type: 'object',
    required: ['url', 'name'],
    properties: {
        name: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const $HomeUrl = {
    type: 'object',
    required: ['url', 'name', 'primaire', 'imgUrl'],
    properties: {
        imgUrl: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        primaire: {
            type: 'boolean'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const $Page = {
    type: 'object',
    required: ['name', 'content', 'metadata'],
    properties: {
        content: {
            type: 'string'
        },
        metadata: {
            '$ref': '#/components/schemas/DocHeader'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const $PageShort = {
    type: 'object',
    required: ['name', 'path', 'metadata'],
    properties: {
        metadata: {
            '$ref': '#/components/schemas/DocHeader'
        },
        name: {
            type: 'string'
        },
        path: {
            type: 'string'
        }
    }
} as const;