// This file is auto-generated by @hey-api/openapi-ts

export const BlogTimelineSchema = {
    type: 'object',
    description: 'Timeline of the blog space, contain the short representation of the pages.',
    required: ['pages'],
    properties: {
        pages: {
            type: 'object',
            additionalProperties: {
                '$ref': '#/components/schemas/PageShort'
            }
        }
    }
} as const;

export const DocCategorySchema = {
    type: 'object',
    description: 'The recursive structure of the sidebar containing the pages and sub-categories of the documentation.',
    required: ['name', 'has_index', 'sub_categories', 'pages'],
    properties: {
        has_index: {
            type: 'boolean'
        },
        name: {
            type: 'string'
        },
        pages: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/PageShort'
            }
        },
        sub_categories: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DocCategory'
            }
        }
    }
} as const;

export const DocHeaderSchema = {
    type: 'object',
    description: 'Header of a markdown file.',
    required: ['title', 'date'],
    properties: {
        date: {
            type: 'string',
            format: 'date-time'
        },
        description: {
            type: 'string',
            nullable: true
        },
        image: {
            type: 'string',
            nullable: true
        },
        links: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/DocHeaderLink'
            }
        },
        spec: {
            '$ref': '#/components/schemas/DocHeaderSpec'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        techno: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        title: {
            type: 'string'
        },
        weight: {
            type: 'integer',
            format: 'int32'
        },
        writter: {
            '$ref': '#/components/schemas/DocHeaderWritter'
        }
    }
} as const;

export const DocHeaderLinkSchema = {
    type: 'object',
    description: 'Link present in the header of a markdown file.',
    required: ['name', 'url'],
    properties: {
        name: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const DocHeaderSpecSchema = {
    type: 'object',
    description: 'Specification of the header of a markdown file, include the information if a Header is a blog/project/doc.',
    properties: {
        blog: {
            type: 'boolean'
        },
        doc: {
            type: 'boolean'
        },
        project: {
            type: 'boolean'
        }
    }
} as const;

export const DocHeaderWritterSchema = {
    type: 'object',
    description: 'Writer present in the header of a markdown file.',
    required: ['name', 'url', 'avatar'],
    properties: {
        avatar: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const HomeContentSchema = {
    type: 'object',
    description: 'Content of the home page.',
    required: ['name', 'presentation', 'coverTitle', 'cvUrl', 'url', 'history'],
    properties: {
        coverTitle: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        cvUrl: {
            type: 'string'
        },
        history: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/HomeHistory'
            }
        },
        name: {
            type: 'string'
        },
        presentation: {
            type: 'string'
        },
        url: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/HomeUrl'
            }
        }
    }
} as const;

export const HomeHistorySchema = {
    type: 'object',
    description: 'History of the home page, contain a part of the history of Max Batleforc.',
    required: ['title', 'lieux', 'date', 'weight', 'imgUrl', 'description'],
    properties: {
        date: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        imgUrl: {
            type: 'string'
        },
        lieux: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        url: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/HomeHistoryUrl'
            },
            nullable: true
        },
        weight: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const HomeHistoryUrlSchema = {
    type: 'object',
    description: 'Url that should be present on the history.',
    required: ['url', 'name'],
    properties: {
        name: {
            type: 'string'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const HomeUrlSchema = {
    type: 'object',
    description: 'Url that should be present on the home page.',
    required: ['url', 'name', 'primaire', 'imgUrl'],
    properties: {
        imgUrl: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        primaire: {
            type: 'boolean'
        },
        url: {
            type: 'string'
        }
    }
} as const;

export const PageSchema = {
    type: 'object',
    description: 'A page containing the content, metadata and name of the page.',
    required: ['name', 'content', 'metadata'],
    properties: {
        content: {
            type: 'string'
        },
        metadata: {
            '$ref': '#/components/schemas/DocHeader'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const PageShortSchema = {
    type: 'object',
    description: 'Short representation of a page, containing only the metadata and the path to the page.',
    required: ['name', 'path', 'metadata'],
    properties: {
        metadata: {
            '$ref': '#/components/schemas/DocHeader'
        },
        name: {
            type: 'string'
        },
        path: {
            type: 'string'
        }
    }
} as const;