// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { GetTimelineData, GetTimelineResponse, GetDocSidebarData, GetDocSidebarResponse, GetHomeData, GetHomeResponse, GetMediaData, GetPageData, GetPageResponse, GetPageV2Data, GetPageV2Response } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get the blog timeline
 * Get blog timeline with minimal description of each article.
 */
export const getTimeline = <ThrowOnError extends boolean = false>(options?: Options<GetTimelineData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetTimelineResponse, unknown, ThrowOnError>({
        url: '/api/blog',
        ...options
    });
};

/**
 * Get doc sidebar
 * Get doc sidebar with minimal description of each article.
 */
export const getDocSidebar = <ThrowOnError extends boolean = false>(options?: Options<GetDocSidebarData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetDocSidebarResponse, unknown, ThrowOnError>({
        url: '/api/doc',
        ...options
    });
};

/**
 * Get home content
 * Get the content meant for the home page.
 */
export const getHome = <ThrowOnError extends boolean = false>(options?: Options<GetHomeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHomeResponse, unknown, ThrowOnError>({
        url: '/api/home',
        ...options
    });
};

/**
 * Get media from the media folder
 * Get the media asset from the media folder.
 */
export const getMedia = <ThrowOnError extends boolean = false>(options: Options<GetMediaData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
        url: '/api/media',
        ...options
    });
};

/**
 * Get a page content
 * Fetch page's content by page path in DbFolder.
 */
export const getPage = <ThrowOnError extends boolean = false>(options: Options<GetPageData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPageResponse, unknown, ThrowOnError>({
        url: '/api/page',
        ...options
    });
};

/**
 * Get a page content in V2
 * Fetch page's content by page path in DbFolder, return page in the V2 format.
 */
export const getPageV2 = <ThrowOnError extends boolean = false>(options: Options<GetPageV2Data, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPageV2Response, unknown, ThrowOnError>({
        url: '/api/v2/page',
        ...options
    });
};