// This file is auto-generated by @hey-api/openapi-ts

export type BlogTimeline = {
    pages: {
        [key: string]: PageShort;
    };
};

export type DocCategory = {
    has_index: boolean;
    name: string;
    pages: Array<PageShort>;
    sub_categories: Array<DocCategory>;
};

export type DocHeader = {
    date: string;
    description?: string | null;
    links?: Array<DocHeaderLink>;
    spec?: DocHeaderSpec;
    tags?: Array<(string)>;
    techno?: Array<(string)>;
    title: string;
    weight?: number;
};

export type DocHeaderLink = {
    name: string;
    url: string;
};

export type DocHeaderSpec = {
    blog?: boolean;
    doc?: boolean;
    project?: boolean;
};

export type HomeContent = {
    coverTitle: Array<(string)>;
    cvUrl: string;
    history: Array<HomeHistory>;
    name: string;
    presentation: string;
    url: Array<HomeUrl>;
};

export type HomeHistory = {
    date: string;
    description: string;
    imgUrl: string;
    lieux: string;
    title: string;
    url?: Array<HomeHistoryUrl> | null;
    weight: number;
};

export type HomeHistoryUrl = {
    name: string;
    url: string;
};

export type HomeUrl = {
    imgUrl: string;
    name: string;
    primaire: boolean;
    url: string;
};

export type Page = {
    content: string;
    metadata: DocHeader;
    name: string;
};

export type PageShort = {
    metadata: DocHeader;
    name: string;
    path: string;
};

export type QuerryMedia = {
    path: string;
};

export type QuerryPage = {
    path: string;
};

export type GetTimelineResponse = BlogTimeline;

export type GetTimelineError = unknown;

export type GetDocSidebarResponse = DocCategory;

export type GetDocSidebarError = unknown;

export type GetHomeResponse = HomeContent;

export type GetHomeError = unknown;

export type GetMediaData = {
    query: {
        /**
         * Page path
         */
        info: QuerryMedia;
    };
};

export type GetMediaResponse = unknown;

export type GetMediaError = unknown;

export type GetPageData = {
    query: {
        /**
         * Page path
         */
        info: QuerryPage;
    };
};

export type GetPageResponse = Page;

export type GetPageError = unknown;

export type $OpenApiTs = {
    '/api/blog': {
        get: {
            res: {
                /**
                 * Blog Timeline
                 */
                '200': BlogTimeline;
                /**
                 * Internal server error
                 */
                '500': unknown;
            };
        };
    };
    '/api/doc': {
        get: {
            res: {
                /**
                 * Doc Sidebar
                 */
                '200': DocCategory;
                /**
                 * Internal server error
                 */
                '500': unknown;
            };
        };
    };
    '/api/home': {
        get: {
            res: {
                /**
                 * Home Content
                 */
                '200': HomeContent;
                /**
                 * Internal server error
                 */
                '500': unknown;
            };
        };
    };
    '/api/media': {
        get: {
            req: GetMediaData;
            res: {
                /**
                 * Media content
                 */
                '200': unknown;
                /**
                 * Page not found
                 */
                '404': unknown;
                /**
                 * Internal server error
                 */
                '500': unknown;
            };
        };
    };
    '/api/page': {
        get: {
            req: GetPageData;
            res: {
                /**
                 * Page Content
                 */
                '200': Page;
                /**
                 * Page not found
                 */
                '404': unknown;
                /**
                 * Internal server error
                 */
                '500': unknown;
            };
        };
    };
};