# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# rust-clippy is a tool that runs a bunch of lints to catch common
# mistakes in your Rust code and help improve your Rust code.
# More details at https://github.com/rust-lang/rust-clippy
# and https://rust-lang.github.io/rust-clippy/

name: rust-sbom gen

on:
  push:
    branches: ['main']
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'package.json'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  schedule:
    - cron: '50 23 * * *'

jobs:
  rust-sbom:
    name: Run rust-clippy analyzing
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom.json
          format: cyclonedx-json
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: sbom.json
      - name: Push to DepTrack
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverhostname: ${{ secrets.DEPENDENCYTRACK_SERVERHOSTNAME }}
          apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          bomfilename: 'sbom.json'
          project: d2e4343b-4344-4537-830e-fdce096473c4
