name: rust api-lint spectral

on:
  push:
    branches: ['main', '*']
    paths:
      - '**/back/**/*.rs'
      - 'folio_content/**/*'
      - '.spectral.yaml'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ['main']
  schedule:
    - cron: '50 23 * * *'

jobs:
  rust-spectral-analyze:
    name: Run rust-spectral analyzing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Install dependencies
        run: yarn install
      - name: Build swagger
        run: yarn run rust:generate
      - name: Spectral lint
        run: yarn run rust:api-lint
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: spectral-report.sarif
          wait-for-processing: true
